version: '3'

networks:
  fiap-store:
    external: false

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: producao_app
#    restart: always
#    ports:
#      - "8084:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://producao_dbhost:5432/producao_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SERVER_PORT=8080
#
#    networks:
#      - fiap-store

  db:
    image: postgres:15
    restart: always
    container_name: producao_dbhost
    environment:
      - POSTGRES_DB=producao_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"

    networks:
      - fiap-store

  localstack:
    image:  localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,iam
      - DEBUG=1
      - LOCALSTACK_HOST=localhost:4566
      - SQS_ENDPOINT_STRATEGY=off

    volumes:
      - "./localstack:/etc/localstack/init/ready.d:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - fiap-store