apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producao
  labels:
    name: ms-producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-producao
  template:
    metadata:
      labels:
        app: ms-producao
    spec:
      containers:
      - name: ms-producao
        image: olegon/soat1-grupo18-ms-producao:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: spring_data_source_url
        - name: SPRING_DATASOURCE_USERNAME
          value: dbuser # Bad practice. It should be a secret.
        - name: SPRING_DATASOURCE_PASSWORD
          value: dbpassword # Bad practice. It should be a secret.
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_region
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_key
        - name: AWS_SQS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sqs_endpoint
        - name: QUEUE_PEDIDO_RECEBIDO
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sqs_queue_pedido_recebido_arn
        - name: QUEUE_PAGAMENTO_APROVADO
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sqs_queue_pagamento_aprovado_arn
        - name: QUEUE_PAGAMENTO_RECUSADO
          valueFrom:
            configMapKeyRef:
              name: application-config
              key: aws_sqs_queue_pagamento_recusado_arn
        ports:
        - containerPort: 8080
